name: Deploy avec Ansible

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add SSH key to known_hosts
      run: |
        ssh-keyscan -H tanguy.frouin.takima.cloud >> ~/.ssh/known_hosts


    - name: Run Ansible Playbook
      run: ansible-playbook -i ./my-project/ansible/inventories/setup.yml ./my-project/ansible/playbook.yml --ssh-common-args='-o StrictHostKeyChecking=no'
      
