name: Deploy avec Ansible

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Run Ansible Playbook
      run: ansible-playbook -i /my-project/ansible/inventories/setup.yml /my-project/ansible/playbook.yml
      env:
        ANSIBLE_HOST_KEY_CHECKING: False
